// GENERATED by scripts/gen-authz.mjs from the project's OpenAPI contracts
// (specs/design/components/*/openapi.yaml and
// specs/design/components/*/dependencies/*.openapi.yaml).
// Do not edit by hand, and do not retype any of these values anywhere else.
// Re-run `npm run gen` after a contract changes. COMMIT this file: the
// per-component image build cannot see the specs tree.
//
// This table is what a screen is gated on. src/authz/screens.ts names the
// operation each screen LOADS; holding that operation's scope is what makes the
// screen reachable. Nothing else in the app decides that.

import type { Scope } from "./roles.gen";

/** What the gateway demands of a caller before it will pass an operation on. */
export type OperationRequirement =
  | { readonly kind: "public" }
  | { readonly kind: "signedIn" }
  | { readonly kind: "scope"; readonly scope: Scope };

/** "<METHOD> <path template>" as the contract spells it, e.g. "GET /me/claims". Sorted. */
export type OperationKey =
  | "GET /health"
  | "GET /me/balance"
  | "GET /me/bank-account"
  | "GET /me/merchant"
  | "GET /me/payment-requests"
  | "GET /me/payment-requests/{id}"
  | "GET /me/payouts"
  | "GET /me/transactions"
  | "GET /merchants"
  | "GET /payment-links/{linkToken}"
  | "GET /payouts"
  | "GET /transactions"
  | "POST /me/payment-requests"
  | "POST /me/payouts"
  | "POST /me/transactions/{id}/refund"
  | "POST /payment-links/{linkToken}/pay"
  | "PUT /me/bank-account"
  | "PUT /me/merchant";

export const OPERATIONS: Record<OperationKey, OperationRequirement> = {
  "GET /health": { kind: "public" },
  "GET /me/balance": { kind: "scope", scope: "payouts:read" },
  "GET /me/bank-account": { kind: "scope", scope: "bank-accounts:manage" },
  "GET /me/merchant": { kind: "scope", scope: "merchants:read" },
  "GET /me/payment-requests": { kind: "scope", scope: "payment-requests:read" },
  "GET /me/payment-requests/{id}": { kind: "scope", scope: "payment-requests:read" },
  "GET /me/payouts": { kind: "scope", scope: "payouts:read" },
  "GET /me/transactions": { kind: "scope", scope: "transactions:read" },
  "GET /merchants": { kind: "scope", scope: "merchants:read-all" },
  "GET /payment-links/{linkToken}": { kind: "public" },
  "GET /payouts": { kind: "scope", scope: "payouts:read-all" },
  "GET /transactions": { kind: "scope", scope: "transactions:read-all" },
  "POST /me/payment-requests": { kind: "scope", scope: "payment-requests:create" },
  "POST /me/payouts": { kind: "scope", scope: "payouts:create" },
  "POST /me/transactions/{id}/refund": { kind: "scope", scope: "refunds:create" },
  "POST /payment-links/{linkToken}/pay": { kind: "public" },
  "PUT /me/bank-account": { kind: "scope", scope: "bank-accounts:manage" },
  "PUT /me/merchant": { kind: "scope", scope: "merchants:update" },
};

export function isOperationKey(value: string): value is OperationKey {
  return Object.prototype.hasOwnProperty.call(OPERATIONS, value);
}
